name:  Mon premier Pipline CI/CD
on:
  push:
    branches:
      - main

jobs:
  runs-on : ubuntu-latest

  steps: 
    - name : le robot dit bonjour
        run : echo "Bonjour Nabiyou je suis tons prochain robot CI/CD"

    - name: Vérification du système
        run: |
          echo "Voici la machine sur laquelle je tourne :"
          cat /etc/os-release
          
    - name: Vérifier si Docker est prêt pour la suite
        run: docker --version
